name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jackin-project/jackin-role-action@52d91d33851d2f346316264831d1505a4bce57f2 # latest
        with:
          jackin-version: latest-build