name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: jackin-project/validate-agent-action@15ee7a8d515f76cd2bd1a508e2e6de3cf4572a0d # latest
        with:
          jackin-version: latest-build
